name: Git Commands CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  execute-git-commands:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Verify Git Config
      run: |
        git config --list


    - name: Test Runner Connection
      run: |
        echo "If you see this message, the self-hosted runner is connected and executing commands."

