name: Deploy React App to AWS S3

on:
  push:
    branches:
      - dev  # Since your branch is named 'dev', not 'main'.

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # Using Ubuntu 22.04.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        #node-version: '18.17.1'  # Using Node.js version 18.17.1.
        node-version: '16.x'  # Use the latest version of Node.js 16.

    - name: Install Dependencies
      run: npm install
      working-directory: ./client  # Specify the working directory where package.json is located.

    - name: Build
      run: npm run build
      working-directory: ./client  # Specify the working directory for the build context.

    - name: Deploy to AWS S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete  # Make files public and remove old files.
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # Set your bucket name.
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set in GitHub secrets.
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set in GitHub secrets.
        AWS_REGION: 'ap-south-1'  # Your AWS region. Change as needed.
        SOURCE_DIR: 'client/build'  # The directory of your built app, adjusted to the 'client' subdirectory.
